#include fetch-common

INSTIGATOR_DNS_HOST=192.168.0.2.xip.io
INSTIGATOR_HTTP_PORT=80
INSTIGATOR_HTTP_HOST="$INSTIGATOR_DNS_HOST"
INSTIGATOR_HTTP_PATH=/stage1.bin-
INSTIGATOR_HTTP_SUFF=.bin

CLASSICAL_INSERT_ETHERNET_INTERFACE="$INSTIGATOR_ETHERNET_INTERFACE"
CLASSICAL_INSERT_DNS_HOST=DNS:"$INSTIGATOR_DNS_HOST"
CLASSICAL_INSERT_HTTP_PORT=80
CLASSICAL_INSERT_HTTP_HOST="$INSTIGATOR_DNS_HOST"
CLASSICAL_INSERT_HTTP_PATH=/
#CLASSICAL_INSERT_PKEY_AUTH=(now provided by the tighter fingen <-> finhub integration)
CLASSICAL_INSERT_PKEY_MAXL="$(( (1*(1024**2)) ))"

CLASSICAL_STAGE2_DNS_HOST="$CLASSICAL_INSERT_DNS_HOST"
CLASSICAL_STAGE2_HTTP_PORT="$CLASSICAL_INSERT_HTTP_PORT"
CLASSICAL_STAGE2_HTTP_HOST="$CLASSICAL_INSERT_HTTP_HOST"
CLASSICAL_STAGE2_HTTP_PATH="$CLASSICAL_INSERT_HTTP_PATH"

CLASSICAL_LANDER_ETHERNET_INTERFACE="$CLASSICAL_INSERT_ETHERNET_INTERFACE"
CLASSICAL_LANDER_DNS_HOST="$CLASSICAL_INSERT_DNS_HOST"
CLASSICAL_LANDER_HTTP_PARALLELISM=3
CLASSICAL_LANDER_HTTP_PORT="$CLASSICAL_INSERT_HTTP_PORT"
CLASSICAL_LANDER_HTTP_HOST="$CLASSICAL_INSERT_HTTP_HOST"
CLASSICAL_LANDER_HTTP_PATH_DATA=/rootfs.bin-

CLASSICAL_STAGEF_ETHERNET_INTERFACE="$CLASSICAL_LANDER_ETHERNET_INTERFACE"
CLASSICAL_STAGEF_DNS_HOST="$CLASSICAL_LANDER_DNS_HOST"
CLASSICAL_STAGEF_HTTP_PORT="$CLASSICAL_LANDER_HTTP_PORT"
CLASSICAL_STAGEF_HTTP_HOST="$CLASSICAL_LANDER_HTTP_HOST"
CLASSICAL_STAGEF_HTTP_PATH=/
