#!/bin/false

function doit()
{
  (
    set -o xtrace
    set -o errexit
    set -o nounset
    set -o pipefail
    
    ( rm -f ./.config* ) || true
    function _() {
      for i in "$@"
      do
        echo "CONFIG_""$i" >>./.config.allconfig
      done
    }
    _ 64BIT=y
    _ KERNEL_XZ=y BLK_DEV_INITRD=y SYSVIPC=y CROSS_MEMORY_ATTACH=y FHANDLE=y CC_{OPTIMIZE_FOR_PERFORMANCE,STACKPROTECTOR_STRONG}=y SHMEM=y AIO=y ADVISE_SYSCALLS=y USERFAULTFD=y MEMBARRIER=y VM_EVENT_COUNTERS=y
    _ NO_HZ_IDLE=y
    _ MULTIUSER=y KALLSYMS=y PRINTK=y BUG=y BASE_FULL=y FUTEX=y EPOLL=y SIGNALFD=y TIMERFD=y EVENTFD=y
    _ BLOCK=y BLK_DEV_BSG=y
    _ SMP=y X86_FEATURE_NAMES=y DMI=y PREEMPT_VOLUNTARY=y X86_MCE=y X86_MCE_INTEL=y X86_MCE_AMD=y NUMA=y SPARSEMEM_VMEMMAP=y X86_CHECK_BIOS_CORRUPTION=y X86_BOOTPARAM_MEMORY_CORRUPTION_CHECK=y HZ_1000=y KEXEC=y
    _ PCI=y PCIEPORTBUS=y PCIEAER=y PCIEASPM=y PCI_MSI=y ISA_DMA_API=y X86_SYSFB=y
    _ BINFMT_ELF=y BINFMT_SCRIPT=y COREDUMP=y CORE_DUMP_DEFAULT_ELF_HEADERS=y
    _ NET=y
    _ PACKET=y UNIX=y INET=y
    _ DEVTMPFS=y
    _ BLK_DEV=y
    _ BLK_DEV_LOOP=y
    _ BLK_DEV_S{D,R}=y
    _ ACPI=y ACPI_REV_OVERRIDE_POSSIBLE=y ACPI_AC=y ACPI_BATTERY=y ACPI_BUTTON=y ACPI_FAN=y ACPI_DOCK=y ACPI_PROCESSOR=y ACPI_PROCESSOR_AGGREGATOR=y ACPI_THERMAL=y X86_PM_TIMER=y
    _ ATA=y ATA_VERBOSE_ERROR=y SATA_PMP=y SATA_AHCI=y
    _ NETDEVICES=y ETHERNET=y
    _ NET_VENDOR_INTEL=y E1000=y E1000E=y # E1000: qemu, E1000E: d16
    _ TTY=y VT=y CONSOLE_TRANSLATIONS=y VT_CONSOLE=y UNIX98_PTYS=y
    _ SERIAL_8250=y SERIAL_8250_CONSOLE=y SERIAL_8250_PCI=y
    _ USB_SUPPORT=y USB=y USB_DEFAULT_PERSIST=y USB_{E,O,U}HCI_HCD=y USB_EHCI_ROOT_HUB_TT=y USB_EHCI_TT_NEWSCHED=y USB_OHCI_HCD_PCI=y USB_STORAGE=y STORAGE_DEBUG=y USB_UAS=y
    _ IOMMU_SUPPORT=y IRQ_REMAP=y
    _ X86_X2APIC=y # backward
    _ PROC_FS=y PROC_SYSCTL=y PROC_PAGE_MONITOR=y
    _ SYSFS=y
    _ TMPFS=y TMPFS_XATTR=y
    _ MAGIC_SYSRQ=y MAGIC_SYSRQ_DEFAULT_ENABLE=0 PANIC_ON_OOPS=y DEBUG_RODATA=y
    _ PRINTK_TIME=y
    _ ENABLE_{WARN_DEPRECATED,MUST_CHECK}=y
    
    make allnoconfig KCONFIG_ALLCONFIG=./.config.allconfig
  )
}

doit
