MACHINE_NAME=global_veysp_2gb

FINHUB_VARSET=global

#include model-veysp
#include fetch-global

function f_defs()
{
  ROOTSHADOW='*'
  TZDATA_TZ=GMT
  PKEY_COMMON=
  PKEY_ROOT="$PKEY_COMMON"
  PKEY_USER="$PKEY_COMMON"
}

#include arm-common

INSTIGATOR_EMMC_PROBE_WORKAROUND=y

CLASSICAL_INSERT_EMMC_PROBE_WORKAROUND=n

CLASSICAL_LANDER_EMMC_PROBE_WORKAROUND=y
CLASSICAL_LANDER_EMMC_LOCKED_WORKAROUND=y

MANAGE_SSH_HOST_KEY=n
