#include fetch-common

BTPDNS=sentinel.deityguard.org
BTPDIR=/v001

INSTIGATOR_DNS_HOST="$BTPDNS"
INSTIGATOR_HTTP_PORT=80
INSTIGATOR_HTTP_HOST="$BTPDNS"
INSTIGATOR_HTTP_PATH="$BTPDIR"/stage1.bin-
INSTIGATOR_HTTP_SUFF=.bin

CLASSICAL_INSERT_ETHERNET_INTERFACE="$INSTIGATOR_ETHERNET_INTERFACE"
CLASSICAL_INSERT_DNS_HOST=DNS:"$BTPDNS"
CLASSICAL_INSERT_HTTP_PORT=80
CLASSICAL_INSERT_HTTP_HOST="$BTPDNS"
CLASSICAL_INSERT_HTTP_PATH="$BTPDIR"/
#CLASSICAL_INSERT_PKEY_AUTH=(now provided by the tighter fingen <-> finhub integration)
CLASSICAL_INSERT_PKEY_MAXL="$(( (1*(1024**2)) ))"

BHSDNS=storage.bhs1.cloud.ovh.net
BHSDIR=/v1/AUTH_29d7fe21639e427c956c6b5048dfe822/sentinel_v001

CLASSICAL_STAGE2_DNS_HOST=DNS:"$BHSDNS"
CLASSICAL_STAGE2_HTTP_PORT=80
CLASSICAL_STAGE2_HTTP_HOST="$BHSDNS"
CLASSICAL_STAGE2_HTTP_PATH="$BHSDIR"/

CLASSICAL_LANDER_ETHERNET_INTERFACE="$CLASSICAL_INSERT_ETHERNET_INTERFACE"
CLASSICAL_LANDER_DNS_HOST=DNS:"$BHSDNS"
CLASSICAL_LANDER_HTTP_PARALLELISM=3
CLASSICAL_LANDER_HTTP_PORT=80
CLASSICAL_LANDER_HTTP_HOST="$BHSDNS"
CLASSICAL_LANDER_HTTP_PATH_DATA="$BHSDIR"/rootfs.bin-
CLASSICAL_LANDER_RESERVED_AREA_SIZE="$(( (64*(1024**2)) ))"
CLASSICAL_LANDER_RESERVED_AREA_ALIGN="$(( (1*(1024**2)) ))"

CLASSICAL_STAGEF_ETHERNET_INTERFACE="$CLASSICAL_LANDER_ETHERNET_INTERFACE"
CLASSICAL_STAGEF_DNS_HOST=DNS:"$BHSDNS"
CLASSICAL_STAGEF_HTTP_PORT=80
CLASSICAL_STAGEF_HTTP_HOST="$BHSDNS"
CLASSICAL_STAGEF_HTTP_PATH="$BHSDIR"/
