ARCH=x64
MODEL=t400
DEBUG_MODEL=n
BOOT_STYLE=chip
BOOT_ROM_KEEP_SEABIOS=n
BOOT_ROM_PENGUIN=n

STAGE0_MODULES_PLATFORM_SPECIFIC=(_)
STAGE1_MODULES_PLATFORM_SPECIFIC=(_)
STAGE1_MODULES_WITHOUT_AUTO_LOAD=(_)
STAGE3_MODULES_PLATFORM_SPECIFIC=(_)
STAGE3_MODULES_MODPROBE_FAIL_LAX=(_)

STAGE0_MODULES_PLATFORM_SPECIFIC+=({ehci,ohci,uhci}-hcd {ehci,ohci}-{pci,platform} ahci e1000e)
STAGE0_USB_NET=n
STAGE1_MODULES_PLATFORM_SPECIFIC+=(i915) # display
STAGE1_MODULES_PLATFORM_SPECIFIC+=(i8042 atkbd) # keyboard
STAGE1_MODULES_WITHOUT_AUTO_LOAD+=(acpi-cpufreq)
STAGE3_MODULES_PLATFORM_SPECIFIC+=("${STAGE0_MODULES_PLATFORM_SPECIFIC[@]:1}")
STAGE3_MODULES_PLATFORM_SPECIFIC+=("${STAGE1_MODULES_PLATFORM_SPECIFIC[@]:1}")
STAGE3_MODULES_PLATFORM_SPECIFIC+=(acpi-cpufreq)
STAGE3_MODULES_MODPROBE_FAIL_LAX+=()
STAGE3_USB_NET=n

#include model-common

FLASHPAGAN_STRATEGY=wrrd
FLASHPAGAN_SPI_SPEED_HZ=10000000
