ARCH=arm
MODEL=veysp
DEBUG_MODEL=n
COMPATIBLE_ARMVERS=(ca17 ca7)
COMPATIBLE_LINFLVS=(rok)
BOOT_STYLE=chip
BOOT_ROM=veysp.4
BOOT_ROM_PENGUIN=y
LINUX_DTB_NAME=rk3288-veyron-speedy
ETH_HWADDR=""

STAGE0_MODULES_PLATFORM_SPECIFIC=(_)
STAGE1_MODULES_PLATFORM_SPECIFIC=(_)
STAGE1_MODULES_WITHOUT_AUTO_LOAD=(_)
STAGE3_MODULES_PLATFORM_SPECIFIC=(_)
STAGE3_MODULES_MODPROBE_FAIL_LAX=(_)

STAGE0_MODULES_PLATFORM_SPECIFIC+=(phy-rockchip-usb dwc2) # usb
STAGE0_MODULES_PLATFORM_SPECIFIC+=(dw_mmc-rockchip pwrseq_emmc mmc_block) # emmc
STAGE0_USB_NET=y
STAGE1_MODULES_PLATFORM_SPECIFIC+=(i2c-rk3x pwm-rockchip pwm_bl panel-simple amba-clcd phy-rockchip-dp rockchipdrm) # display
STAGE1_MODULES_PLATFORM_SPECIFIC+=(spi-rockchip cros_ec_spi cros_ec_keyb) # keyboard
#STAGE1_MODULES_PLATFORM_SPECIFIC+=(rk808 rk808-regulator) # platform
STAGE1_MODULES_WITHOUT_AUTO_LOAD+=(flush_data_cache)
STAGE3_MODULES_PLATFORM_SPECIFIC+=("${STAGE0_MODULES_PLATFORM_SPECIFIC[@]:1}")
STAGE3_MODULES_PLATFORM_SPECIFIC+=("${STAGE1_MODULES_PLATFORM_SPECIFIC[@]:1}")
STAGE3_USB_NET=y

MODEL_VEYSP_4GB=n

#include model-common

FLASHPAGAN_STRATEGY=conv
FLASHPAGAN_SPI_SPEED_HZ=5000000
