ARCH=arm
MODEL=banpi
DEBUG_MODEL=n
COMPATIBLE_ARMVERS=(ca7)
COMPATIBLE_LINFLVS=(bpi)
BOOT_STYLE=fel
U_BOOT_BOARD_NAME=Bananapi
LINUX_DTB_NAME=sun7i-a20-bananapi
ETH_HWADDR=""

STAGEF_MODULES_PLATFORM_SPECIFIC=(_)
STAGE3_MODULES_PLATFORM_SPECIFIC=(_)
STAGE3_MODULES_MODPROBE_FAIL_LAX=(_)

STAGEF_MODULES_PLATFORM_SPECIFIC+=(dwmac-sunxi realtek) # eth
STAGEF_MODULES_PLATFORM_SPECIFIC+=(fbcon) # display
STAGE3_MODULES_PLATFORM_SPECIFIC+=("${STAGEF_MODULES_PLATFORM_SPECIFIC[@]:1}")
STAGE3_MODULES_PLATFORM_SPECIFIC+=(i2c-mv64xxx axp20x_usb_power {ehci,ohci}_platform sunxi) # usb
STAGE3_MODULES_PLATFORM_SPECIFIC+=(hid-generic usbhid) # hid
STAGE3_MODULES_PLATFORM_SPECIFIC+=(axp20x-i2c) # usb (depending on kernel version)
STAGE3_MODULES_MODPROBE_FAIL_LAX+=(axp20x-i2c)
STAGE3_USB_NET=y

STAGEF_AUTONOMOUS=n

#include model-common
