LINUX_CMDLINE="console=tty1"

INSTIGATOR_DRIVE_SETTLE_SECONDS=3

if [ "$DEBUG_MODEL" == "y" ]
then
  INSTIGATOR_DRIVE_SETTLE_SECONDS=0
fi

INSTIGATOR_ETHERNET_INTERFACE=eth0

STAGE2_SKIP_KEXEC=n
STAGE2_USE_STAGE1_KEXEC=y

INSTIGATOR_EMMC_PROBE_WORKAROUND=n

CLASSICAL_INSERT_EMMC_PROBE_WORKAROUND=n

CLASSICAL_LANDER_EMMC_PROBE_WORKAROUND=n
CLASSICAL_LANDER_EMMC_LOCKED_WORKAROUND=n

CLASSICAL_INSERT_BYPASS=n
CLASSICAL_LANDER_BYPASS=n
